### ISSUE TITLE
UnboundLocalError: local variable 'objs' referenced before assignment

### ISSUE THREAD

**Issue by exp0nge** [davedash/django-fixture-magic#34]
Here's the trace when running dump_object with `app.a_model '*' > fixture.json`
![image](https://cloud.githubusercontent.com/assets/11747245/11611202/22fa9180-9b8f-11e5-895f-917ebc1ec05f.png)

**Comment by faustow** [comment]
Having the same issue myself, here's the traceback in text format:
`(venv)m1@m1:~/app-django$ python manage.py dump_object -k app.FirstModel * > fausto.json
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/m1/app-django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/m1/app-django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/m1/app-django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/m1/app-django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/m1/app-django/venv/local/lib/python2.7/site-packages/fixture_magic/management/commands/dump_object.py", line 73, in handle
    for obj in objs:
UnboundLocalError: local variable 'objs' referenced before assignment
`

**Comment by dchoruzy** [comment]
same error occurred to me

**Comment by jerzygangi** [comment]
I'm having the same issue

**Comment by davedash** [comment]
@jerzygangi can you try out the version in https://github.com/davedash/django-fixture-magic/tree/possible-fix and let me know if that works for you? 

It's an edge case, but I don't have a good way of testing it.

**Comment by fleur** [comment]
i'm having the same problem as exp0nge, which looks like it's happening in a different place in the code than faustow's.  the possible-fix branch doesn't fix my issue, fwiw.

**Comment by jerzygangi** [comment]
@davedash Sorry for the delay in replying. I wish I could help... I stopped using fixture magic, and started writing fixtures by hand; also, quite some time has passed so I'm not sure I could reproduce the bug again. Good luck in figuring it out.
